Repository i-go-algo/i-go-algo, pull requests merged in 2022-09, with the labels that each got.

#44 22.08.29 (yeonju)
  BOJ/15686-치킨_배달/15686-치킨_배달-yeonju.py
  BOJ/16953-A_→_B/16953-A_→_B-yeonju.py
Labels: 연주 :rabbit:

#42 22.08.27(Changjun)
  BOJ/15686-치킨_배달/15686-치킨_배달-changjun.py
  BOJ/16953-A_→_B/16953-A_→_B-changjun.py
  BOJ/17070-파이프_옮기기_1/17070-파이프_옮기기_1-changjun.py
Labels: 창준 :panda_face:

#43 22.08.28 (yoonseok)
  BOJ/02263-트리의_순회/02263-트리의_순회-yoonseok.py
  BOJ/11404-플로이드/11404-플로이드-yoonseok.py
  BOJ/13549-숨바꼭질_3/13549-숨바꼭질_3-yoonseok.py
  BOJ/14938-서강그라운드/14938-서강그라운드-yoonseok.py
  BOJ/15686-치킨_배달/15686-치킨_배달-yoonseok.py
  BOJ/16953-A_→_B/16953-A_→_B-yoonseok.py
  BOJ/17070-파이프_옮기기_1/17070-파이프_옮기기_1-yoonseok.py
Labels: 윤석 :cat:

#41 22.08.27(eonyong)
  BOJ/15686-치킨_배달/15686-치킨_배달-eonyong.py
  BOJ/16953-A_→_B/16953-A_→_B-eonyong.py
  BOJ/17144-미세먼지_안녕!/17144-미세먼지_안녕!-eonyong.py
Labels: 언용 :dragon:

#45 22.09.03 (eonyong)
  BOJ/03190-뱀/03190-뱀-eonyong.py
  BOJ/13458-시험_감독/13458-시험_감독-eonyong.py
  BOJ/14499-주사위_굴리기/14499-주사위_굴리기-eonyong.py
  BOJ/14501-퇴사/14501-퇴사-eonyong.py
  BOJ/17144-미세먼지_안녕!/17144-미세먼지_안녕!-eonyong.py
Labels: 언용 :dragon:

#46 22.09.05 (Yeonju)
  .github/PULL_REQUEST_TEMPLATE.md
  .github/auto_assign.yml
  BOJ/02263-트리의_순회/02263-트리의_순회-yoonseok.py
  BOJ/03190-뱀/03190-뱀-changjun.py
  BOJ/03190-뱀/03190-뱀-eonyong.py
  BOJ/03190-뱀/03190-뱀-yeonju.py
  BOJ/03190-뱀/03190-뱀-yoonseok.py
  BOJ/03190-뱀/README.md
  BOJ/11404-플로이드/11404-플로이드-yoonseok.py
  BOJ/13458-시험_감독/13458-시험_감독-changjun.py
  BOJ/13458-시험_감독/13458-시험_감독-eonyong.py
  BOJ/13458-시험_감독/13458-시험_감독-yeonju.py
  BOJ/13458-시험_감독/13458-시험_감독-yoonseok.py
  BOJ/13458-시험_감독/README.md
  BOJ/13549-숨바꼭질_3/13549-숨바꼭질_3-yoonseok.py
  BOJ/14499-주사위_굴리기/14499-주사위_굴리기-changjun.py
  BOJ/14499-주사위_굴리기/14499-주사위_굴리기-eonyong.py
  BOJ/14499-주사위_굴리기/14499-주사위_굴리기-yeonju.py
  BOJ/14499-주사위_굴리기/14499-주사위_굴리기-yoonseok.py
  BOJ/14499-주사위_굴리기/README.md
  BOJ/14500-테트로미노/14500-테트로미노-changjun.py
  BOJ/14500-테트로미노/14500-테트로미노-eonyong.py
  BOJ/14500-테트로미노/14500-테트로미노-yeonju.py
  BOJ/14500-테트로미노/14500-테트로미노-yoonseok.py
  BOJ/14500-테트로미노/README.md
  BOJ/14501-퇴사/14501-퇴사-changjun.py
  BOJ/14501-퇴사/14501-퇴사-eonyong.py
  BOJ/14501-퇴사/14501-퇴사-yeonju.py
  BOJ/14501-퇴사/14501-퇴사-yoonseok.py
  BOJ/14501-퇴사/README.md
  BOJ/14503-로봇_청소기/14503-로봇_청소기-changjun.py
  BOJ/14503-로봇_청소기/14503-로봇_청소기-eonyong.py
  BOJ/14503-로봇_청소기/14503-로봇_청소기-yeonju.py
  BOJ/14503-로봇_청소기/14503-로봇_청소기-yoonseok.py
  BOJ/14503-로봇_청소기/README.md
  BOJ/14888-연산자_끼워넣기/14888-연산자_끼워넣기-changjun.py
  BOJ/14888-연산자_끼워넣기/14888-연산자_끼워넣기-eonyong.py
  BOJ/14888-연산자_끼워넣기/14888-연산자_끼워넣기-yeonju.py
  BOJ/14888-연산자_끼워넣기/14888-연산자_끼워넣기-yoonseok.py
  BOJ/14888-연산자_끼워넣기/README.md
  BOJ/14889-스타트와_링크/14889-스타트와_링크-changjun.py
  BOJ/14889-스타트와_링크/14889-스타트와_링크-eonyong.py
  BOJ/14889-스타트와_링크/14889-스타트와_링크-yeonju.py
  BOJ/14889-스타트와_링크/14889-스타트와_링크-yoonseok.py
  BOJ/14889-스타트와_링크/README.md
  BOJ/14890-경사로/14890-경사로-changjun.py
  BOJ/14890-경사로/14890-경사로-eonyong.py
  BOJ/14890-경사로/14890-경사로-yeonju.py
  BOJ/14890-경사로/14890-경사로-yoonseok.py
  BOJ/14890-경사로/README.md
  BOJ/14938-서강그라운드/14938-서강그라운드-yoonseok.py
  BOJ/15686-치킨_배달/15686-치킨_배달-changjun.py
  BOJ/15686-치킨_배달/15686-치킨_배달-eonyong.py
  BOJ/15686-치킨_배달/15686-치킨_배달-yoonseok.py
  BOJ/16953-A_→_B/16953-A_→_B-changjun.py
  BOJ/16953-A_→_B/16953-A_→_B-eonyong.py
  BOJ/16953-A_→_B/16953-A_→_B-yoonseok.py
  BOJ/17070-파이프_옮기기_1/17070-파이프_옮기기_1-changjun.py
  BOJ/17070-파이프_옮기기_1/17070-파이프_옮기기_1-yoonseok.py
  BOJ/17144-미세먼지_안녕!/17144-미세먼지_안녕!-eonyong.py
Labels: 연주 :rabbit:

#47 22.09.07 (Yoonseok)
  BOJ/13458-시험_감독/13458-시험_감독-yoonseok.py
  BOJ/14500-테트로미노/14500-테트로미노-yoonseok.py
  BOJ/14501-퇴사/14501-퇴사-yoonseok.py
Labels: 윤석 :cat:

#50 22.09.14(Eonyong)
  BOJ/01107-리모컨/01107-리모컨-eonyong.py
  BOJ/14502-연구소/14502-연구소-eonyong.py
  BOJ/14503-로봇_청소기/14503-로봇_청소기-eonyong.py
  BOJ/14888-연산자_끼워넣기/14888-연산자_끼워넣기-eonyong.py
  BOJ/14889-스타트와_링크/14889-스타트와_링크-eonyong.py
Labels: 언용 :dragon:

#54 22.09.19 (yeonju)
  BOJ/14891-톱니바퀴/14891-톱니바퀴-yeonju.py
  BOJ/15683-감시/15683-감시-yeonju.py
  BOJ/15684-사다리_조작/15684-사다리_조작-yeonju.py
Labels: 연주 :rabbit:

#53 22.09.16 (eonyong)
  BOJ/14891-톱니바퀴/14891-톱니바퀴-eonyong.py
  BOJ/15683-감시/15683-감시-eonyong.py
  BOJ/15684-사다리_조작/15684-사다리_조작-eonyong.py
Labels: 언용 :dragon:

#56 22.09.26 (yoonseok)
  BOJ/16234-인구_이동/16234-인구_이동-yoonseok.py
  BOJ/16235-나무_재테크/16235-나무_재테크-yoonseok.py
  BOJ/16236-아기_상어/16236-아기_상어-yoonseok.py
Labels: 윤석 :cat:

#58 22.09.26 (Eonyong)
  BOJ/16234-인구_이동/16234-인구_이동-eonyong.py
  BOJ/16236-아기_상어/16236-아기_상어-eonyong.py
  BOJ/17140-이차원_배열과_연산/17140-이차원_배열과_연산-eonyong.py
Labels: 언용 :dragon:

#57 22.09.27 (yeonju)
  .github/PULL_REQUEST_TEMPLATE.md
  BOJ/16234-인구_이동/16234-인구_이동-yeonju.py
  BOJ/16236-아기_상어/16236-아기_상어-yeonju.py
  BOJ/17140-이차원_배열과_연산/17140-이차원_배열과_연산-yeonju.py
  BOJ/17142-연구소_3/17142-연구소_3-eonyong.py
  BOJ/17142-연구소_3/17142-연구소_3-yeonju.py
  BOJ/17142-연구소_3/17142-연구소_3-yoonseok.py
  BOJ/17142-연구소_3/README.md
  BOJ/17779-게리맨더링_2/17779-게리맨더링_2-eonyong.py
  BOJ/17779-게리맨더링_2/17779-게리맨더링_2-yeonju.py
  BOJ/17779-게리맨더링_2/17779-게리맨더링_2-yoonseok.py
  BOJ/17779-게리맨더링_2/README.md
  BOJ/17822-원판_돌리기/17822-원판_돌리기-eonyong.py
  BOJ/17822-원판_돌리기/17822-원판_돌리기-yeonju.py
  BOJ/17822-원판_돌리기/17822-원판_돌리기-yoonseok.py
  BOJ/17822-원판_돌리기/README.md
  BOJ/17825-주사위_윷놀이/17825-주사위_윷놀이-eonyong.py
  BOJ/17825-주사위_윷놀이/17825-주사위_윷놀이-yeonju.py
  BOJ/17825-주사위_윷놀이/17825-주사위_윷놀이-yoonseok.py
  BOJ/17825-주사위_윷놀이/README.md
  BOJ/17837-새로운_게임_2/17837-새로운_게임_2-eonyong.py
  BOJ/17837-새로운_게임_2/17837-새로운_게임_2-yeonju.py
  BOJ/17837-새로운_게임_2/17837-새로운_게임_2-yoonseok.py
  BOJ/17837-새로운_게임_2/README.md
Labels: 연주 :rabbit:
