Repository i-go-algo/i-go-algo, pull requests merged in 2022-10, with the labels that each got.

#59 22.09.30 (eonyong)
  BOJ/17140-이차원_배열과_연산/17140-이차원_배열과_연산-eonyong.py
  BOJ/17142-연구소_3/17142-연구소_3-eonyong.py
  BOJ/17779-게리맨더링_2/17779-게리맨더링_2-eonyong.py
  BOJ/17822-원판_돌리기/17822-원판_돌리기-eonyong.py
Labels: 언용 :dragon:

#61 22.10.03 (yoonseok)
  BOJ/17142-연구소_3/17142-연구소_3-yoonseok.py
  BOJ/17825-주사위_윷놀이/17825-주사위_윷놀이-yoonseok.py
  BOJ/17837-새로운_게임_2/17837-새로운_게임_2-yoonseok.py
Labels: 윤석 :cat:

#60 22.10.03 (yeonju)
  .github/PULL_REQUEST_TEMPLATE.md
  BOJ/17142-연구소_3/17142-연구소_3-yeonju.py
  BOJ/17779-게리맨더링_2/17779-게리맨더링_2-yeonju.py
  BOJ/17837-새로운_게임_2/17837-새로운_게임_2-yeonju.py
  BOJ/21611-마법사_상어와_블리자드/21611-마법사_상어와_블리자드-eonyong.py
  BOJ/21611-마법사_상어와_블리자드/21611-마법사_상어와_블리자드-yeonju.py
  BOJ/21611-마법사_상어와_블리자드/21611-마법사_상어와_블리자드-yoonseok.py
  BOJ/21611-마법사_상어와_블리자드/README.md
  BOJ/23288-주사위_굴리기_2/23288-주사위_굴리기_2-eonyong.py
  BOJ/23288-주사위_굴리기_2/23288-주사위_굴리기_2-yeonju.py
  BOJ/23288-주사위_굴리기_2/23288-주사위_굴리기_2-yoonseok.py
  BOJ/23288-주사위_굴리기_2/README.md
  BOJ/23289-온풍기_안녕!/23289-온풍기_안녕!-eonyong.py
  BOJ/23289-온풍기_안녕!/23289-온풍기_안녕!-yeonju.py
  BOJ/23289-온풍기_안녕!/23289-온풍기_안녕!-yoonseok.py
  BOJ/23289-온풍기_안녕!/README.md
  BOJ/23290-마법사_상어와_복제/23290-마법사_상어와_복제-eonyong.py
  BOJ/23290-마법사_상어와_복제/23290-마법사_상어와_복제-yeonju.py
  BOJ/23290-마법사_상어와_복제/23290-마법사_상어와_복제-yoonseok.py
  BOJ/23290-마법사_상어와_복제/README.md
  BOJ/23291-어항_정리/23291-어항_정리-eonyong.py
  BOJ/23291-어항_정리/23291-어항_정리-yeonju.py
  BOJ/23291-어항_정리/23291-어항_정리-yoonseok.py
  BOJ/23291-어항_정리/README.md
Labels: 연주 :rabbit:

#62 22.10.09 (eonyong)
  BOJ/21611-마법사_상어와_블리자드/21611-마법사_상어와_블리자드-eonyong.py
  BOJ/23288-주사위_굴리기_2/23288-주사위_굴리기_2-eonyong.py
  BOJ/23290-마법사_상어와_복제/23290-마법사_상어와_복제-eonyong.py
  BOJ/23291-어항_정리/23291-어항_정리-eonyong.py
Labels: 언용 :dragon:

#63 22.10.09 (yoonseok)
  BOJ/19236-청소년_상어/19236-청소년_상어-yoonseok.py
  BOJ/19238-스타트_택시/19238-스타트_택시-yoonseok.py
  BOJ/20055-컨베이어_벨트_위의_로봇/20055-컨베이어_벨트_위의_로봇-yoonseok.py
  BOJ/21611-마법사_상어와_블리자드/21611-마법사_상어와_블리자드-yoonseok.py
  BOJ/23288-주사위_굴리기_2/23288-주사위_굴리기_2-yoonseok.py
  BOJ/23291-어항_정리/23291-어항_정리-yoonseok.py
Labels: 윤석 :cat:

#65 22.10.20 (yeonju)
  .github/PULL_REQUEST_TEMPLATE.md
  BOJ/20055-컨베이어_벨트_위의_로봇/20055-컨베이어_벨트_위의_로봇-yeonju.py
  BOJ/20056-마법사_상어와_파이어볼/20056-마법사_상어와_파이어볼-eonyong.py
  BOJ/20056-마법사_상어와_파이어볼/20056-마법사_상어와_파이어볼-yeonju.py
  BOJ/20056-마법사_상어와_파이어볼/20056-마법사_상어와_파이어볼-yoonseok.py
  BOJ/20056-마법사_상어와_파이어볼/README.md
  BOJ/20057-마법사_상어와_토네이도/20057-마법사_상어와_토네이도-eonyong.py
  BOJ/20057-마법사_상어와_토네이도/20057-마법사_상어와_토네이도-yeonju.py
  BOJ/20057-마법사_상어와_토네이도/20057-마법사_상어와_토네이도-yoonseok.py
  BOJ/20057-마법사_상어와_토네이도/README.md
  BOJ/20058-마법사_상어와_파이어스톰/20058-마법사_상어와_파이어스톰-eonyong.py
  BOJ/20058-마법사_상어와_파이어스톰/20058-마법사_상어와_파이어스톰-yeonju.py
  BOJ/20058-마법사_상어와_파이어스톰/20058-마법사_상어와_파이어스톰-yoonseok.py
  BOJ/20058-마법사_상어와_파이어스톰/README.md
  BOJ/21608-상어_초등학교/21608-상어_초등학교-eonyong.py
  BOJ/21608-상어_초등학교/21608-상어_초등학교-yeonju.py
  BOJ/21608-상어_초등학교/21608-상어_초등학교-yoonseok.py
  BOJ/21608-상어_초등학교/README.md
  BOJ/21609-상어_중학교/21609-상어_중학교-eonyong.py
  BOJ/21609-상어_중학교/21609-상어_중학교-yeonju.py
  BOJ/21609-상어_중학교/21609-상어_중학교-yoonseok.py
  BOJ/21609-상어_중학교/README.md
Labels: 연주 :rabbit:

#68 22.10.24 (yoonseok)
  BOJ/14891-톱니바퀴/14891-톱니바퀴-yoonseok.py
  BOJ/16234-인구_이동/16234-인구_이동-yoonseok.py
  BOJ/17140-이차원_배열과_연산/17140-이차원_배열과_연산-yoonseok.py
  BOJ/20056-마법사_상어와_파이어볼/20056-마법사_상어와_파이어볼-yoonseok.py
  BOJ/21608-상어_초등학교/21608-상어_초등학교-yoonseok.py
  BOJ/21609-상어_중학교/21609-상어_중학교-yoonseok.py
Labels: 윤석 :cat:

#66 22.10.24 (eonyong)
  BOJ/20055-컨베이어_벨트_위의_로봇/20055-컨베이어_벨트_위의_로봇-eonyong.py
  BOJ/20056-마법사_상어와_파이어볼/20056-마법사_상어와_파이어볼-eonyong.py
  BOJ/21608-상어_초등학교/21608-상어_초등학교-eonyong.py
  BOJ/21609-상어_중학교/21609-상어_중학교-eonyong.py
Labels: 언용 :dragon:

#67 22.10.24 (yeonju)
  .github/PULL_REQUEST_TEMPLATE.md
  BOJ/01005-ACM_Craft/01005-ACM_Craft-eonyong.py
  BOJ/01005-ACM_Craft/01005-ACM_Craft-yeonju.py
  BOJ/01005-ACM_Craft/01005-ACM_Craft-yoonseok.py
  BOJ/01005-ACM_Craft/README.md
  BOJ/01007-벡터_매칭/01007-벡터_매칭-eonyong.py
  BOJ/01007-벡터_매칭/01007-벡터_매칭-yeonju.py
  BOJ/01007-벡터_매칭/01007-벡터_매칭-yoonseok.py
  BOJ/01007-벡터_매칭/README.md
  BOJ/01197-최소_스패닝_트리/01197-최소_스패닝_트리-eonyong.py
  BOJ/01197-최소_스패닝_트리/01197-최소_스패닝_트리-yeonju.py
  BOJ/01197-최소_스패닝_트리/01197-최소_스패닝_트리-yoonseok.py
  BOJ/01197-최소_스패닝_트리/README.md
  BOJ/01202-보석_도둑/01202-보석_도둑-eonyong.py
  BOJ/01202-보석_도둑/01202-보석_도둑-yeonju.py
  BOJ/01202-보석_도둑/01202-보석_도둑-yoonseok.py
  BOJ/01202-보석_도둑/README.md
  BOJ/01208-부분수열의_합_2/01208-부분수열의_합_2-eonyong.py
  BOJ/01208-부분수열의_합_2/01208-부분수열의_합_2-yeonju.py
  BOJ/01208-부분수열의_합_2/01208-부분수열의_합_2-yoonseok.py
  BOJ/01208-부분수열의_합_2/README.md
  BOJ/20058-마법사_상어와_파이어스톰/20058-마법사_상어와_파이어스톰-yeonju.py
  BOJ/21608-상어_초등학교/21608-상어_초등학교-yeonju.py
  BOJ/21609-상어_중학교/21609-상어_중학교-yeonju.py
Labels: 연주 :rabbit:
