Repository i-go-algo/i-go-algo, pull requests merged in 2022-06, with the labels that each got.

#2 22.06.24(yoonseok)
  BOJ/01003-피보나치_함수/01003-피보나치_함수-yoonseok.py
  BOJ/01012-유기농_배추/01012-유기농_배추-yoonseok.py
  BOJ/01074-Z/01074-Z-yoonseok.py
  BOJ/01107-리모컨/01107-리모컨-yoonseok.py
  BOJ/01260-DFS와_BFS/01260-DFS와_BFS-yoonseok.py
  BOJ/01389-케빈_베이컨의_6단계_법칙/01389-케빈_베이컨의_6단계_법칙-yoonseok.py
  BOJ/01463-1로_만들기/01463-1로_만들기-yoonseok.py
Labels: 윤석 :cat:, 오늘좀멋져 :sunglasses:

#3 22.06.24 (yeonju)
  BOJ/01003-피보나치_함수/01003-피보나치_함수-yeonju.py
  BOJ/01012-유기농_배추/01012-유기농_배추-yeonju.py
  BOJ/01107-리모컨/01107-리모컨-yeonju.py
  BOJ/01260-DFS와_BFS/01260-DFS와_BFS-yeonju.py
  BOJ/01389-케빈_베이컨의_6단계_법칙/01389-케빈_베이컨의_6단계_법칙-yeonju.py
  BOJ/01463-1로_만들기/01463-1로_만들기-yeonju.py
Labels: 연주 :rabbit:, 오늘좀멋져 :sunglasses:

#4 22.06.25(eonyong)
  .DS_Store
  BOJ/.DS_Store
  BOJ/01003-피보나치_함수/01003-피보나치_함수-eonyong.py
  BOJ/01012-유기농_배추/01012-유기농_배추-eonyong.py
  BOJ/01074-Z/01074-Z-eonyong.py
  BOJ/01107-리모컨/01107-리모컨-eonyong.py
  BOJ/01389-케빈_베이컨의_6단계_법칙/01389-케빈_베이컨의_6단계_법칙-eonyong.py
  BOJ/01463-1로_만들기/01463-1로_만들기-eonyong.py
Labels: 언용 :dragon:, 오늘좀멋져 :sunglasses:

#1 22.06.23 (changjun)
  BOJ/01003-피보나치_함수/01003-피보나치_함수-changjun.py
  BOJ/01012-유기농_배추/01012-유기농_배추-changjun.py
  BOJ/01074-Z/01074-Z-changjun.py
  BOJ/01107-리모컨/01107-리모컨-changjun.py
  BOJ/01260-DFS와_BFS/01260-DFS와_BFS-changjun.py
  BOJ/01389-케빈_베이컨의_6단계_법칙/01389-케빈_베이컨의_6단계_법칙-changjun.py
  BOJ/01463-1로_만들기/01463-1로_만들기-changjun.py
Labels: 창준 :panda_face:, 오늘좀멋져 :sunglasses:
