Repository i-go-algo/i-go-algo, pull requests merged in 2022-08, with the labels that each got.

#28 22.08.04 (Eonyong)
  BOJ/02407-조합/02407-조합-eonyong.py
  BOJ/02448-별_찍기_-_11/02448-별_찍기_-_11-eonyong.py
  BOJ/02638-치즈/02638-치즈-eonyong.py
  BOJ/09251-LCS/09251-LCS-eonyong.py
Labels: 언용 :dragon:

#27 22.07.31 (Yoon seok)
  BOJ/02206-벽_부수고_이동하기/02206-벽_부수고_이동하기-yoonseok.py
  BOJ/02263-트리의_순회/02263-트리의_순회-yoonseok.py
  BOJ/02407-조합/02407-조합-yoonseok.py
  BOJ/09251-LCS/09251-LCS-yoonseok.py
Labels: 윤석 :cat:

#25 22.07.30 (Yeonju)
  BOJ/02206-벽_부수고_이동하기/02206-벽_부수고_이동하기-yeonju.py
  BOJ/02407-조합/02407-조합-yeonju.py
  BOJ/02638-치즈/02638-치즈-yeonju.py
  BOJ/05639-이진_검색_트리/05639-이진_검색_트리-yeonju.py
  BOJ/09251-LCS/09251-LCS-yeonju.py
Labels: 연주 :rabbit:

#26 22.07.31 (Changjun)
  BOJ/02206-벽_부수고_이동하기/02206-벽_부수고_이동하기-changjun.py
  BOJ/02407-조합/02407-조합-changjun.py
  BOJ/02638-치즈/02638-치즈-changjun.py
  BOJ/09251-LCS/09251-LCS-changjun.py
Labels: 창준 :panda_face:

#32 22.08.10 (Yoon seok)
  BOJ/02263-트리의_순회/02263-트리의_순회-yoonseok.py
  BOJ/02407-조합/02407-조합-yoonseok.py
  BOJ/09465-스티커/09465-스티커-yoonseok.py
  BOJ/09663-N-Queen/09663-N-Queen-yoonseok.py
  BOJ/11053-가장_긴_증가하는_부분_수열/11053-가장_긴_증가하는_부분_수열-yoonseok.py
  BOJ/11404-플로이드/11404-플로이드-yoonseok.py
Labels: 윤석 :cat:

#31 22.08.07 (Yeonju)
  BOJ/09465-스티커/09465-스티커-yeonju.py
  BOJ/09663-N-Queen/09663-N-Queen-yeonju.py
  BOJ/09935-문자열_폭발/09935-문자열_폭발-yeonju.py
  BOJ/11053-가장_긴_증가하는_부분_수열/11053-가장_긴_증가하는_부분_수열-yeonju.py
  BOJ/11404-플로이드/11404-플로이드-yeonju.py
Labels: 연주 :rabbit:

#30 22.08.07 (Changjun)
  BOJ/09465-스티커/09465-스티커-changjun.py
  BOJ/09465-스티커/09465-스티커-yoonseok.py
  BOJ/09663-N-Queen/09663-N-Queen-changjun.py
  BOJ/09663-N-Queen/09663-N-Queen-yeonju.py
  BOJ/09663-N-Queen/09663-N-Queen-yoonseok.py
  BOJ/09935-문자열_폭발/09935-문자열_폭발-changjun.py
  BOJ/10830-행렬_제곱/10830-행렬_제곱-changjun.py
  BOJ/11053-가장_긴_증가하는_부분_수열/11053-가장_긴_증가하는_부분_수열-yoonseok.py
  BOJ/11404-플로이드/11404-플로이드-yoonseok.py
Labels: 창준 :panda_face:

#29 22.08.07 (Eonyong)
  BOJ/02407-조합/02407-조합-eonyong.py
  BOJ/09663-N-Queen/09663-N-Queen-eonyong.py
  BOJ/09935-문자열_폭발/09935-문자열_폭발-eonyong.py
  BOJ/10830-행렬_제곱/10830-행렬_제곱-eonyong.py
  BOJ/11404-플로이드/11404-플로이드-eonyong.py
Labels: 언용 :dragon:

#36 22.08.15 (Yeonju)
  BOJ/11660-구간_합_구하기_5/11660-구간_합_구하기_5-yeonju.py
  BOJ/11725-트리의_부모_찾기/11725-트리의_부모_찾기-yeonju.py
  BOJ/12851-숨바꼭질_2/12851-숨바꼭질_2-yeonju.py
  BOJ/12865-평범한_배낭/12865-평범한_배낭-yeonju.py
Labels: 연주 :rabbit:

#35 22.08.14 (eonyong)
  BOJ/11660-구간_합_구하기_5/11660-구간_합_구하기_5-eonyong.py
  BOJ/11725-트리의_부모_찾기/11725-트리의_부모_찾기-eonyong.py
  BOJ/11779-최소비용_구하기_2/11779-최소비용_구하기_2-eonyong.py
  BOJ/12865-평범한_배낭/12865-평범한_배낭-eonyong.py
Labels: 언용 :dragon:

#33 22.08.14 (Changjun)
  BOJ/11660-구간_합_구하기_5/11660-구간_합_구하기_5-changjun.py
  BOJ/11725-트리의_부모_찾기/11725-트리의_부모_찾기-changjun.py
  BOJ/12851-숨바꼭질_2/12851-숨바꼭질_2-changjun.py
  BOJ/12865-평범한_배낭/12865-평범한_배낭-changjun.py
Labels: 창준 :panda_face:

#34 22.08.14 (Yoonseok)
  BOJ/11444-피보나치_수_6/11444-피보나치_수_6-yoonseok.py
  BOJ/11660-구간_합_구하기_5/11660-구간_합_구하기_5-yoonseok.py
  BOJ/11725-트리의_부모_찾기/11725-트리의_부모_찾기-yoonseok.py
  BOJ/12865-평범한_배낭/12865-평범한_배낭-yoonseok.py
Labels: 윤석 :cat:

#37 22.08.20 (Eonyong)
  BOJ/14502-연구소/14502-연구소-eonyong.py
  BOJ/15650-N과_M_(2)/15650-N과_M_(2)-eonyong.py
  BOJ/15652-N과_M_(4)/15652-N과_M_(4)-eonyong.py
  BOJ/15654-N과_M_(5)/15654-N과_M_(5)-eonyong.py
  BOJ/15657-N과_M_(8)/15657-N과_M_(8)-eonyong.py
  BOJ/15663-N과_M_(9)/15663-N과_M_(9)-eonyong.py
  BOJ/15666-N과_M_(12)/15666-N과_M_(12)-eonyong.py
Labels: 언용 :dragon:

#39 22.08.20 (Changjun)
  BOJ/15650-N과_M_(2)/15650-N과_M_(2)-changjun.py
  BOJ/15652-N과_M_(4)/15652-N과_M_(4)-changjun.py
  BOJ/15654-N과_M_(5)/15654-N과_M_(5)-changjun.py
  BOJ/15657-N과_M_(8)/15657-N과_M_(8)-changjun.py
  BOJ/15663-N과_M_(9)/15663-N과_M_(9)-changjun.py
  BOJ/15666-N과_M_(12)/15666-N과_M_(12)-changjun.py
Labels: 창준 :panda_face:

#38 22.08.22 (Yoonseok)
  BOJ/13549-숨바꼭질_3/13549-숨바꼭질_3-yoonseok.py
  BOJ/14938-서강그라운드/14938-서강그라운드-yoonseok.py
  BOJ/15650-N과_M_(2)/15650-N과_M_(2)-yoonseok.py
  BOJ/15652-N과_M_(4)/15652-N과_M_(4)-yoonseok.py
Labels: 윤석 :cat:
